### ISSUE TITLE
NodeSchool #4 (duben 2015)

### ISSUE THREAD

**Issue by bajtos** [nodeschool/hradec-kralove#7]
Původně jsem chtěl v dubnu jenom zopakovat úvod do JavaScriptu a Node.js. Tím pádem by však dubnová NodeSchool nebyla zajímavá pro lidi, kteří už mají úvod za sebou.

Napadlo mě proto, že bychom mohli udělat dvě paralelní části: úvod do Node.js pro "nováčky", a pak něco jiného pro "pokročilé". Co vy na to?

Které téma by pro vás bylo nejzajímavější?

 1. Funkcionální styl programování
 2. Browserify aneb Node.js v browseru
 3. EcmaScript 6 (a.k.a ES 2015) a io.js: promises & generators
 
@nodeschool/hradec-kralove napište prosím váš názor do komentáře, dejme si termín do 2.3.2015.

**Comment by pdostal** [comment]
Já se přikláním za ***1. Funkcionální styl programování*** - jsem stále v začátcích a je myslím dobré naučit se pořádně základy než hned postupovat dál.

**Comment by MicTech** [comment]
Já jsem také pro Funkcionální programování v JavaScriptu.

**Comment by PetrHavelka** [comment]
Pokud to bude něco jako přednáška s workshopem tak rad prijdu . Preferoval
bych funkcionální programovani a promisy. Ale pokud to bude jen link na
samostatnou práci, tak me to nelaka. Tu si mohu udělat i doma sam.

Petr
Dne 23.2.2015 18:38 "Michal Těhník" <notifications@github.com> napsal(a):

**Comment by novoj** [comment]
Také jsem pro variantu 1)

**Comment by lcir** [comment]
Myslím, že varianta 1. by byla fajn

**Comment by tpuza** [comment]
Za me taky varianta #1, nicmene uvod by me taky zajimal. Uvod jsem nevidel,  protoze jsem jsem jeste o techle akcich nevedel.  Cloveku obcas pri samostudiu u uniknou dulezite zaklady nebo je dobre si nektere pripomenout.

**Comment by bajtos** [comment]
@PetrHavelka Jakou máš představu o přednášce, co by ses chtěl dozvědět? Umím si představit, že bych úvodní povídání rozšířil o dalších 5-10 minut a udělal krátký teoretický úvod k tomu, co se bude následně procvičovat. Jinak obecně NodeSchool bude vždy hlavně o té samostatné práci. Pro přednášky viz [GDG HK](http://www.gug.cz/cs/gdg/skupiny/hradec-kralove).

Ještě drobné upřesnění k tomu funkcionálnímu stylu programování: nejedná se o hard-core FP s immutable strukturami, spíš se naučit používat `array.map` and `array.filter` místo psaní for-cyklů. Píšu to proto, aby jste pak nebyli zklamání.

**Comment by jakubmatena** [comment]
Za mě určitě 1 nebo 2.

**Comment by bajtos** [comment]
Děkuji všem za komentáře. Dubnová NodeSchool bude mít tedy dvě souběžné témata:

- Pro nováčky zopakujeme úvodní lekci, ve které se seznámíte se základy JavaScriptu a Node.js. Tato lekce je vhodná zejména pro ty, kteří ještě nemají žádné zkušenosti s JavaScriptem a Node.js.

- Pro ostřílené účastníky bude k dispozici workshop na procvičení práce s funkcemi, skládání funkcí a používání primitiv typu „map“ nebo „filter“ místo for-cyklů.

Workshop začnu krátkou přednáškou a až pak bude následovat samostatná práce na cvičeních.

Nezapomeňte se prosím zaregistrovat na [srazy.info](http://srazy.info/nodeschool/5086)

Na viděnou v dubnu!

/cc @nodeschool/hradec-kralove

**Comment by bajtos** [comment]
## Poznámky z retrospektivy

**plus**
 - úvodní povídání dodalo kontext x3
 - skvělé příklady
 - Miro chodil často mezi lidmi a nabízel pomoc x2
 - výběr cvičení (možnost volby)

**delta**
 - všichni stejné cvičení
 - trochu víc času
 - pracovat párově, víc u toho mluvit, víc spolupracovat
 - rozdělit lidi do skupin podle cvičení, které dělají
 - Miro má mluvit hlasitěji když přednáší
 - udělat základ cvičení společně
 - nápad na jiný formát: rozdělit se do několika týmů, každý z týmů pracuje na části většího celku, na konci se dílčí kousky spojí to výsledného celku

**Comment by yangwao** [comment]
dobré poznámky! :)
