### ISSUE TITLE
International Day - sobota 23.5.2015

### ISSUE THREAD

**Issue by bajtos** [nodeschool/hradec-kralove#8]
V sobotu 23. 5. 2015 se bude konat [mezinárodní den NodeSchool](http://nodeschool.io/international-day/), květnová NodeSchool proto bude netradičně na celý den.

Rád bych přitáhl větší počet účastníků, ideálně aby se naplnila kapacita CoolWorkingu - cca 30 lidí. V takovém počtu to už nezvládnu sám, potřebuji další lidi kteří budou schopni radit a pomáhat ostatním účastníkům.

**Oslovuji proto vás, kteří jste si už NodeSchool prošli - kdo jste ochoten pomoct a stát se lektorem?**

#### Předběžný harmonogram:

  - **09.00** - 09.15 Registrace, občerstvení, networking. 
  - 09.15 - 09.30 Úvodní povídání.
  - 09.30 - 11.30 **První iterace.**
  - 11.30 - 13.00 Networking, oběd.
  - 13.00 - 15.00 **Druhá iterace.**
  - 15.00 - 15.30 Pauza, občerstvení, networking.
  - 15.30 - 17.30 **Třetí iterace.**
  - 17.30 - **18.00** Závěr.
  - hospoda

Relativně pozdější začátek zjednoduší cestování přespolním, z Prahy stačí vyjet vlakem v 7.10.

#### Předběžný seznam témat:

 - Úvod do JS a Node.js: javascripting, learnyounode, planetproto
 - Flow control: async-you, promise-it-wont-hurt
 - Functional JS: functional-javascript-workshop, lololodash
 - LoopBack: http://bit.ly/learn-loopback

K tomu chci přidat něco nového, třeba:

 - Visuální hrátky: introtowebgl, webgl-workshop, shader-school
 - ES6: count-to-6, learn-generators
 - Node.js v browseru:  browserify-adventure
 - Streams: stream-adventure
 - Porovnání HTTP frameworků: expressworks, makemehapi, kick-off-koa

Na březnové NodeSchool jsme se bavili o tom, že je dobré začít krátkým povídáním které představí jednotlivé lekce (dobrodružství). 

**Měl byste někdo chuť pomoct mi i tady a připravit si přednášku na cca 2-5 minut o některém z těchto nových témat?**

@nodeschool/hradec-kralove @abtris @MicTech

**Comment by bajtos** [comment]
Pokud máte kdokoliv nápad, co udělat jinak a lépe, tak sem s ním! Stejně tak s dotazy.

**Comment by abtris** [comment]
@bajtos ja muzu, rezervoval jsem si na to cas. Muzu udelat treba to porovnani http frameworku

**Comment by MicTech** [comment]
@bajtos Zatim mam kalendar prazdny, ale stejne musim rict "may be", protoze nevim, kam me moje prace posle za 2 mesice.

**Comment by lcir** [comment]
@bajtos počítej se mnou, rád ti pomůžu, minimálně po stránce orgaanizační.

**Comment by bajtos** [comment]
@abtris @lcir díky, počítám s vámi. @MicTech chápu, dej pak vědět až budeš mít jasno.

Vytvořil jsem termín na srazy.info, viz http://srazy.info/nodeschool/5323

@abtris počítám tedy s tím, že předneseš krátké srovnání HTTP frameworků. Můžeš do toho zahrnout i LoopBack? Nebo bude lepší, když LoopBack představím já?

Zahrnul jsem do programu 3D grafiku, ať to není všechno jenom suché programování backendu. Začal bych https://github.com/alexmackey/IntroToWebGLWithThreeJS, vypadá to docela jednoduše. Uvažoval jsem i o https://github.com/stackgl/shader-school, ale to je už asi moc hard-cord. @lcir měl bys chuť (a čas) se podívat na [Three.js](http://threejs.org/) a udělat krátké představení? Když ne, tak to snad zvládnu i sám.

@nodeschool/hradec-kralove chtěl bych vás poprosit o pomoc s propagací. Máte někdo kontakt na lidi ze zdrojak.cz? Nápady na jiné portály pro vývojáře, kde bychom mohli dát vědět o této akci?

**Comment by abtris** [comment]
@bajtos Asi to zahrnu, pripadne rozsireni muzes dat ty.

**Comment by bajtos** [comment]
> @bajtos Asi to zahrnu, pripadne rozsireni muzes dat ty.

Super. Zakladni informace najdes na http://loopback.io/ a taky http://www.slideshare.net/Bajtos/loopback-a-productivity-booster-for-mean.

**Comment by lcir** [comment]
@bajtos To by šlo, kouknu na to.

**Comment by jakubmatena** [comment]
@bajtos Miro, předběžně se mnou můžeš počítat. Ještě se ujistím, že na tu sobotu skutečně nic plánovaného nemám. Co se týče prezentace, tak bych mohl zkusit připravit něco na 5min na: "Node.js v browseru: browserify-adventure". Ještě se kouknu o co přesně jde.

**Comment by bajtos** [comment]
@jakubmatena to by bylo super! browserify-adventure je o http://browserify.org/. V prezentaci můžeš zmínit taky http://webpack.github.io/ . Další čtení: [browserify for webpack users] (https://gist.github.com/substack/68f8d502be42d5cd4942).

**Comment by jakubmatena** [comment]
@bajtos já si to myslel, ale nebyl jsem si jistý, jestli jde opravdu o tohle. O webpacku malé povědomí mám, takže se o tom můžu taky zmínit. Jinak 23.května mám vyhrazené na tuhle akci, takže se mnou počítej ;-)

**Comment by robinpokorny** [comment]
Ahoj, se mnou také počítej! (Pokud už nemáš dost lidí)

Myslel jsem, že bych si mohl připravit něco o ES2015. Především o těch částech, které nejsou jen _syntax sugar_.

**Comment by bajtos** [comment]
@robinpokorny 
> Ahoj, se mnou také počítej! (Pokud už nemáš dost lidí)

Super, každý další lektor se hodí.

> Myslel jsem, že bych si mohl připravit něco o ES2015. Především o těch částech, které nejsou jen syntax sugar.

Důležité je, aby se přednáška potkávala s obsahem cvičení. Jestli se nepletu, tak [count-to-6](https://github.com/domenic/count-to-6/blob/master/lib/exercises/menu.json) pokrývá zejména syntax sugar.

Myslím, že nabídku cvičení máme teď už dost širokou, tak bych ES6 radši nechal na jindy.

Na podzim můžeme udělat večerní NodeSchool zaměřenou jenom na ES6 - count-to-6, promises a k tomu tvoje povídání o dalších zajímavých věcech z ES6. Co ty na to?

**Comment by robinpokorny** [comment]
@bajtos: Jasně, chápu. Podzim můžeme promyslet. Jak bych tedy mohl pomoct?

**Comment by bajtos** [comment]
> Jak bych tedy mohl pomoct?

Stačí dorazit a být k dispozici pro ostatní účastníky, pokud se někde zaseknou a budou potřebovat pomoct :)

**Comment by octopuss** [comment]
Tak webpacku se klidne chopim ja :) jen potrebuji vedet rozsah v jakem to
ma byt

**Comment by bajtos** [comment]
> @octopuss Tak webpacku se klidne chopim ja :) jen potrebuji vedet rozsah v jakem to
ma byt

Pro webpack zatím není žádné cvičení (viz http://nodeschool.io/#workshoppers) a navíc už máme na programu browserify (viz https://github.com/nodeschool/hradec-kralove/issues/8#issuecomment-91644814 od @jakubmatena), takže samostatná přednáška o webpacku se teď nehodí.

Smyslem přednášek je udělat úvod k praktickým cvičením, aby lidi věděli, co si vlastně zkoušejí. Kde není cvičení (workshopper), tam nemá smysl dělat přednášku.

ALE: Jestli máš chuť se podělit o znalosti webpacku, tak se zkus domluvit s @lcir, který organizuje přednášky v rámci [Google Developer Group](http://www.gug.cz/cs/gdg/skupiny/hradec-kralove). Třeba si můžete spolu s @jakubmatena připravit každý jednu středně dlouhou přednášku na 30-40 minut.

**Comment by bajtos** [comment]
Ahoj, 23. květen se blíží, pro jistotu připomínám rozdělení přednášek:

@bajtos
 - Otevírací řeč, úvod to JavaScriptu a Node.js
 - Flow Control, Functional JavaScript 
 
@abtris 
 - Porovnání HTTP frameworků: Express, Hapi, Koa, LoopBack

@jakubmatena 
 - Node.js v browseru (browserify-adventure)

@lcir 
 - 3D grafika a Three.js

Snažte se prosím povídání co nejvíc zkrátit a zjednodušit, abyste se vešli do 3-5 minut.

---

Ostatní organizační záležitosti bych měl zvládnout sám. Prostory CoolWorkingu máme domluvené, zbývá:

 - [ ] Napsat do CoolWorkingu objednávku pití.
 - [ ] Objednat a vyzvednout drobné sladké občerstvení v pekárně u nás za domem
 - [ ] Domluvit dovoz oběda, vytisknout "menu" pro objednávku
 - [ ] Zarezervovat hospodu

**Comment by lcir** [comment]
@bajtos všechny přednášky chceš odbavit hned na začátku?

**Comment by jakubmatena** [comment]
@bajtos Miro, o víkendu si budu zkoušet browserify-adventure, protože jsem si tam v komentářích všimnul, že možná ne úplně vše je v tom úkolu při kontrole správnosti správně zkontrolováno a tedy teoreticky s neověřitelným řešením.

**Comment by bajtos** [comment]
> @lcir  všechny přednášky chceš odbavit hned na začátku?

Ano, to je můj původní plán. Jestli dodržíme limit 5 minut, tak se celé povídání vejde do cca 25 minut.

Jestli máš nějaký nápad, jak (a proč) to udělat lépe, tak sem s ním!

> @jakubmatena  Miro, o víkendu si budu zkoušet browserify-adventure, protože jsem si tam v komentářích všimnul, že možná ne úplně vše je v tom úkolu při kontrole správnosti správně zkontrolováno a tedy teoreticky s neověřitelným řešením.

Hmm :-| Dej prosím po víkendu vědět, co jsi zjistil, ať můžeme rozmyslet, jak nejlépe postupovat dál. Tahkle z hlavy mě napadá, že problém může být taky s verzí browserify. Za poslední rok udělali několik nekompatibilních změn, je možné že workshop nebyl aktualizovaný? Jestli jo, tak bych zkusil verzi 3.x.

**Comment by jakubmatena** [comment]
@bajtos Miro, tak jsem si to o víkendu prošel. Z těch 10 úkolů jsem stihnul 9, z čehož jsem si s jedním nevěděl moc rady (nevzdal jsem to hned, ale asi po 2h už mě to přestalo bavit), ale zbylých 8 šlo dát dohromady. Kdyby si měl čas, tak jde o 8. úlohu využitím toho, co se napsalo v 7. úloze.

**Comment by bajtos** [comment]
@jakubmatena zkousel si se podivat na vzorove reseni? Reseni je sice trochu nezvykle, zejmena pokud clovek neni zvykly na praci se Stream API, ale prijde mi jako docela dobre citelne a pochopitelne:

https://github.com/substack/browserify-adventure/blob/79d5ea0447287bca1c43ecd5a83a2360d1d7a270/problems/writing_transforms/solution.txt

**Comment by jakubmatena** [comment]
@bajtos Koukal jsem to a zkoušel jsem použít přímo to vzorové řešení, které mimochodem nefunguje, protože nevrací Transform stream (alespoň to píše node). Nakonec jsem to předevčírem ještě asi po hodince bádání dal nějakým svým způsobem za použití toho řešení předtím.

**Comment by bajtos** [comment]
Díky všem za pomoc s organizací!

## Poznámky ze závěrečné retrospektivy

**Plus**
 - zopakování základů, funkcionální programování
 - WebGL x2
 - příležitost zeptat se zkušenějších x2
 - hodně úkolů na výběr, jejich rozmanitost x3
 - React.js adventure
 - rychlá pomoc při záseku x2
 - formát x2

**Delta**
 - víc konzultací a pomáhání (organizátoři byly často jinde) 
 - lepší úvodní popis adventures, kde se budou hodit získané znalosti, aby si člověk uměl lépe vybrat
 - nedokonalé testy u některých cvičení
 - přechod mezi začátečníkem a pokročilým byl moc strmý
 - doporučená trať, v jakém pořadí dělat adventures
 - zařadit taky cvičení na streams/pipes
 - víc tlačit párové programování
 - rozdělit prezentaci/povídání a zařadit něco i odpoledne
 - WebGL - jak to běhá (?)
 - ovoce
 - rozdělit na skupiny, udělat přednášky nepovinné
 - některé cvičení by měli dávat lepší feedback o tom, co dělá program špatně
 - některé cvičení (zejména FP) jsou moc dlouhé
 - častější a formálnější přestávky
 - visačky se jmény
 - organizovat  akci častěji
